# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 629)
        MainWindow.setMinimumSize(QtCore.QSize(478, 170))
        MainWindow.setMaximumSize(QtCore.QSize(778, 629))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_box = QtWidgets.QLineEdit(self.centralwidget)
        self.search_box.setGeometry(QtCore.QRect(10, 161, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.search_box.setFont(font)
        self.search_box.setText("")
        self.search_box.setObjectName("search_box")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(440, 160, 33, 33))
        self.search_btn.setText("")
        self.search_btn.setObjectName("search_btn")
        self.jobsiteaccount_frame = QtWidgets.QScrollArea(self.centralwidget)
        self.jobsiteaccount_frame.setGeometry(QtCore.QRect(10, 10, 461, 141))
        self.jobsiteaccount_frame.setWidgetResizable(True)
        self.jobsiteaccount_frame.setObjectName("jobsiteaccount_frame")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 459, 139))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.jobsite_select = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.jobsite_select.setGeometry(QtCore.QRect(114, 55, 211, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.jobsite_select.setFont(font)
        self.jobsite_select.setObjectName("jobsite_select")
        self.jobsitepassword_box = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.jobsitepassword_box.setGeometry(QtCore.QRect(114, 109, 236, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.jobsitepassword_box.setFont(font)
        self.jobsitepassword_box.setText("")
        self.jobsitepassword_box.setObjectName("jobsitepassword_box")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_4.setGeometry(QtCore.QRect(47, 109, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.jobsiteusername_box = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.jobsiteusername_box.setGeometry(QtCore.QRect(114, 83, 236, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.jobsiteusername_box.setFont(font)
        self.jobsiteusername_box.setText("")
        self.jobsiteusername_box.setObjectName("jobsiteusername_box")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_5.setGeometry(QtCore.QRect(42, 83, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_6.setGeometry(QtCore.QRect(2, 54, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verify_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.verify_btn.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.verify_btn.setText("")
        self.verify_btn.setObjectName("verify_btn")
        self.jobsiteaccountcancel_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.jobsiteaccountcancel_btn.setGeometry(QtCore.QRect(327, 54, 24, 24))
        self.jobsiteaccountcancel_btn.setText("")
        self.jobsiteaccountcancel_btn.setObjectName("jobsiteaccountcancel_btn")
        self.play_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.play_btn.setGeometry(QtCore.QRect(90, 10, 40, 40))
        self.play_btn.setText("")
        self.play_btn.setObjectName("play_btn")
        self.delete_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.delete_btn.setGeometry(QtCore.QRect(130, 10, 40, 40))
        self.delete_btn.setText("")
        self.delete_btn.setObjectName("delete_btn")
        self.gotosite_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.gotosite_btn.setGeometry(QtCore.QRect(170, 10, 40, 40))
        self.gotosite_btn.setText("")
        self.gotosite_btn.setObjectName("gotosite_btn")
        self.stop_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.stop_btn.setGeometry(QtCore.QRect(50, 10, 40, 40))
        self.stop_btn.setText("")
        self.stop_btn.setObjectName("stop_btn")
        self.playload_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.playload_lbl.setGeometry(QtCore.QRect(90, 10, 40, 40))
        self.playload_lbl.setText("")
        self.playload_lbl.setObjectName("playload_lbl")
        self.pauseload_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.pauseload_lbl.setGeometry(QtCore.QRect(50, 10, 40, 40))
        self.pauseload_lbl.setText("")
        self.pauseload_lbl.setObjectName("pauseload_lbl")
        self.deleteload_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.deleteload_lbl.setGeometry(QtCore.QRect(130, 10, 40, 40))
        self.deleteload_lbl.setText("")
        self.deleteload_lbl.setObjectName("deleteload_lbl")
        self.verifyload_lbl = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.verifyload_lbl.setGeometry(QtCore.QRect(9, 10, 40, 40))
        self.verifyload_lbl.setText("")
        self.verifyload_lbl.setObjectName("verifyload_lbl")
        self.todo_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.todo_btn.setGeometry(QtCore.QRect(360, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.todo_btn.setFont(font)
        self.todo_btn.setFlat(False)
        self.todo_btn.setObjectName("todo_btn")
        self.processed_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.processed_btn.setGeometry(QtCore.QRect(360, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.processed_btn.setFont(font)
        self.processed_btn.setFlat(False)
        self.processed_btn.setObjectName("processed_btn")
        self.applied_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.applied_btn.setGeometry(QtCore.QRect(360, 90, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.applied_btn.setFont(font)
        self.applied_btn.setFlat(False)
        self.applied_btn.setObjectName("applied_btn")
        self.todoforsite_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.todoforsite_btn.setGeometry(QtCore.QRect(210, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.todoforsite_btn.setFont(font)
        self.todoforsite_btn.setFlat(False)
        self.todoforsite_btn.setObjectName("todoforsite_btn")
        self.shrink_expand_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.shrink_expand_btn.setGeometry(QtCore.QRect(10, 83, 21, 21))
        self.shrink_expand_btn.setText("")
        self.shrink_expand_btn.setObjectName("shrink_expand_btn")
        self.moreinfo_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.moreinfo_btn.setGeometry(QtCore.QRect(10, 109, 21, 21))
        self.moreinfo_btn.setText("")
        self.moreinfo_btn.setObjectName("moreinfo_btn")
        self.appliedforsite_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.appliedforsite_btn.setGeometry(QtCore.QRect(280, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.appliedforsite_btn.setFont(font)
        self.appliedforsite_btn.setFlat(False)
        self.appliedforsite_btn.setObjectName("appliedforsite_btn")
        self.play_btn.raise_()
        self.delete_btn.raise_()
        self.verify_btn.raise_()
        self.stop_btn.raise_()
        self.gotosite_btn.raise_()
        self.jobsite_select.raise_()
        self.jobsitepassword_box.raise_()
        self.label_4.raise_()
        self.jobsiteusername_box.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.jobsiteaccountcancel_btn.raise_()
        self.playload_lbl.raise_()
        self.pauseload_lbl.raise_()
        self.deleteload_lbl.raise_()
        self.verifyload_lbl.raise_()
        self.todo_btn.raise_()
        self.processed_btn.raise_()
        self.applied_btn.raise_()
        self.todoforsite_btn.raise_()
        self.shrink_expand_btn.raise_()
        self.moreinfo_btn.raise_()
        self.appliedforsite_btn.raise_()
        self.jobsiteaccount_frame.setWidget(self.scrollAreaWidgetContents_5)
        self.matchup_table = QtWidgets.QTableWidget(self.centralwidget)
        self.matchup_table.setGeometry(QtCore.QRect(480, 370, 291, 141))
        self.matchup_table.setObjectName("matchup_table")
        self.matchup_table.setColumnCount(0)
        self.matchup_table.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 350, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.suggkeywords_box = QtWidgets.QLineEdit(self.centralwidget)
        self.suggkeywords_box.setGeometry(QtCore.QRect(480, 530, 291, 61))
        self.suggkeywords_box.setObjectName("suggkeywords_box")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(550, 510, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 200, 461, 391))
        self.tabs.setObjectName("tabs")
        self.jobs = QtWidgets.QWidget()
        self.jobs.setObjectName("jobs")
        self.jobs_table = QtWidgets.QTableWidget(self.jobs)
        self.jobs_table.setGeometry(QtCore.QRect(-1, -1, 459, 362))
        self.jobs_table.setObjectName("jobs_table")
        self.jobs_table.setColumnCount(0)
        self.jobs_table.setRowCount(0)
        self.tabs.addTab(self.jobs, "")
        self.suggkeywordsload_lbl = QtWidgets.QLabel(self.centralwidget)
        self.suggkeywordsload_lbl.setGeometry(QtCore.QRect(480, 530, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.suggkeywordsload_lbl.setFont(font)
        self.suggkeywordsload_lbl.setText("")
        self.suggkeywordsload_lbl.setObjectName("suggkeywordsload_lbl")
        self.matchupload_lbl = QtWidgets.QLabel(self.centralwidget)
        self.matchupload_lbl.setGeometry(QtCore.QRect(480, 370, 291, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.matchupload_lbl.setFont(font)
        self.matchupload_lbl.setText("")
        self.matchupload_lbl.setObjectName("matchupload_lbl")
        self.jobprofile_table = QtWidgets.QTableWidget(self.centralwidget)
        self.jobprofile_table.setGeometry(QtCore.QRect(480, 40, 291, 311))
        self.jobprofile_table.setObjectName("jobprofile_table")
        self.jobprofile_table.setColumnCount(0)
        self.jobprofile_table.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(580, 0, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.log_listbox = QtWidgets.QListWidget(self.centralwidget)
        self.log_listbox.setGeometry(QtCore.QRect(10, 430, 461, 161))
        self.log_listbox.setObjectName("log_listbox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 410, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.delete_ujobs_on_jprofile_edit_check = QtWidgets.QCheckBox(self.centralwidget)
        self.delete_ujobs_on_jprofile_edit_check.setGeometry(QtCore.QRect(500, 20, 241, 20))
        self.delete_ujobs_on_jprofile_edit_check.setObjectName("delete_ujobs_on_jprofile_edit_check")
        self.search_box.raise_()
        self.search_btn.raise_()
        self.jobsiteaccount_frame.raise_()
        self.matchup_table.raise_()
        self.label_3.raise_()
        self.suggkeywords_box.raise_()
        self.label_8.raise_()
        self.suggkeywordsload_lbl.raise_()
        self.matchupload_lbl.raise_()
        self.jobprofile_table.raise_()
        self.label_2.raise_()
        self.log_listbox.raise_()
        self.label.raise_()
        self.tabs.raise_()
        self.delete_ujobs_on_jprofile_edit_check.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jobbybot"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.label_6.setText(_translate("MainWindow", "Job Site Account"))
        self.gotosite_btn.setToolTip(_translate("MainWindow", "go to the job site"))
        self.gotosite_btn.setWhatsThis(_translate("MainWindow", "go to the job site"))
        self.playload_lbl.setToolTip(_translate("MainWindow", "start autoapply onsite"))
        self.pauseload_lbl.setToolTip(_translate("MainWindow", "stop autoapply onsite"))
        self.todo_btn.setToolTip(_translate("MainWindow", "# of jobs todo"))
        self.todo_btn.setWhatsThis(_translate("MainWindow", "# of jobs todo"))
        self.todo_btn.setText(_translate("MainWindow", "todo"))
        self.processed_btn.setToolTip(_translate("MainWindow", "# of processed jobs"))
        self.processed_btn.setWhatsThis(_translate("MainWindow", "# of processed jobs"))
        self.processed_btn.setText(_translate("MainWindow", "processed"))
        self.applied_btn.setToolTip(_translate("MainWindow", "# of applied jobs"))
        self.applied_btn.setWhatsThis(_translate("MainWindow", "# of applied jobs"))
        self.applied_btn.setText(_translate("MainWindow", "applied"))
        self.todoforsite_btn.setToolTip(_translate("MainWindow", "# of jobs todo for this site"))
        self.todoforsite_btn.setWhatsThis(_translate("MainWindow", "# of jobs todo for this site"))
        self.todoforsite_btn.setText(_translate("MainWindow", "todo"))
        self.shrink_expand_btn.setToolTip(_translate("MainWindow", "shrink or expand the window"))
        self.moreinfo_btn.setToolTip(_translate("MainWindow", "show event log"))
        self.appliedforsite_btn.setToolTip(_translate("MainWindow", "# of jobs applied for this site"))
        self.appliedforsite_btn.setWhatsThis(_translate("MainWindow", "# of jobs applied for this site"))
        self.appliedforsite_btn.setText(_translate("MainWindow", "todo"))
        self.label_3.setText(_translate("MainWindow", "Jobs Matching Your Profile"))
        self.label_8.setText(_translate("MainWindow", "Suggested Keywords"))
        self.tabs.setTabText(self.tabs.indexOf(self.jobs), _translate("MainWindow", "Jobs"))
        self.label_2.setText(_translate("MainWindow", "Job Profile"))
        self.label.setText(_translate("MainWindow", "Log"))
        self.delete_ujobs_on_jprofile_edit_check.setText(_translate("MainWindow", "delete old unprocessed jobs on job profile edit"))

